<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">
	
	<title>Login</title>
	
	<!-- Bootstrap core CSS -->
	<link href="bower_components/bootstrap/dist/css/bootstrap.css" rel="stylesheet">
	<link href="css/ie10-viewport-bug-workaround.css" rel="stylesheet">
	<link href="css/main.css" rel="stylesheet">
    <script src="bower_components/sweetalert/dist/sweetalert.min.js"></script>
    <link rel="stylesheet" type="text/css" href="bower_components/sweetalert/dist/sweetalert.css">  
    
</head>
<body id="login_page">
    <div id="header">
       <a class="center-block" href="../templates/projects.php">
                    <img src="images/PC-logo.png" id="logo" alt="">
        </a>
  </div>
  </div>
    </div>
    <?php if(isset($_SESSION["user"])){unset($_SESSION['user']);} ?>
        <div class="container">    
            <div id="loginbox" style="margin-top:100px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">                    
                <div class="panel panel-default" id="panel-default">
                        <div class="panel-heading" id="panel-heading">
                            <div class="panel-title">Sign In</div>
                            <div style="float:right; font-size: 80%; position: relative; top:-10px"><a href="#">Forgot password?</a></div>
                        </div>     

                        <div style="padding-top:30px" class="panel-body" >

                            <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>
                                
                            <form id="loginform" enctype="multipart/form-data" name="logForm" class="form-horizontal" role="form" method="POST" onsubmit="return login();">
                                        
                                <div style="margin-bottom: 25px" class="input-group">
                                            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                            <input id="email" type="text" class="form-control" name="email" value="" placeholder="Email" >                                      
                                        </div>
                                    
                                <div style="margin-bottom: 25px" class="input-group">
                                            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                                            <input id="password" type="password" class="form-control" name="password" placeholder="Password">
                                        </div>
                                        
                                <!-- #messages is where the messages are placed inside -->
                                <div class="form-group">
                                    <div class="col-md-9 col-md-offset-3">
                                        <div id="messages"></div>
                                    </div>
                                </div>


                                    <div style="margin-top:10px" class="form-group">
                                        <!-- Button -->

                                        <div class="col-sm-12 controls">
                                            <button type="button" id="btn-login" class="btn btn-info" value="Login">Login</button>
                                        </div>
                                        
                                    </div>
                                    <div style="margin-top:10px" class="form-group">
                                        <!-- Button -->

                                        <div class="col-sm-12 controls">
                                        <button type="button" id="btn-guest" class="btn btn-info" value="SignUp">Sign in as Guest</button>
                                        </div>
                                        
                                    </div>


                                    <div class="form-group">
                                        <div class="col-md-12 control">
                                            <div style="border-top: 1px solid#888; padding-top:15px; font-size:85%" >
                                                Don't have an account! 
                                            <a href="#" onClick="$('#loginbox').hide(); $('#signupbox').show()">
                                                Sign Up Here
                                            </a>
                                            </div>
                                        </div>
                                    </div>    
                                </form>     



                            </div>                     
                        </div>  
            </div>
            <div id="signupbox" style="display:none; margin-top:100px" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                        <div class="panel panel-default" id="panel-default">
                            <div class="panel-heading" id="panel-heading">
                                <div class="panel-title">Sign Up</div>
                                <div style="float:right; font-size: 85%; position: relative; top:-10px"><a id="signinlink" href="" onclick="$('#signupbox').hide(); $('#loginbox').show()">Sign In</a></div>
                            </div>  
                            <div class="panel-body" >
                                <form id="signupform" enctype="multipart/form-data"  class="form-horizontal" role="form" method="POST" action="index.php/signup">
                                    
                                    <div id="signupalert" style="display:none" class="alert alert-danger">
                                        <p>Error:</p>
                                        <span></span>
                                    </div>
                                        
                                    
                                    
                                    <div class="form-group">
                                        <label for="email" class="col-md-3 control-label">Email</label>
                                        <div class="col-md-9">
                                            <input type="text" id="email" class="form-control" name="email" placeholder="Email Address">
                                        </div>
                                    </div>
                                        
                                    <div class="form-group">
                                        <label for="firstname" class="col-md-3 control-label">First Name</label>
                                        <div class="col-md-9">
                                            <input type="text" id="fname" class="form-control" name="fname" placeholder="First Name">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="lastname" class="col-md-3 control-label">Last Name</label>
                                        <div class="col-md-9">
                                            <input type="text" id="lname" class="form-control" name="lname" placeholder="Last Name">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="password" class="col-md-3 control-label">Password</label>
                                        <div class="col-md-9">
                                            <input type="password" id="password" class="form-control" name="password" placeholder="Password">
                                        </div>
                                    </div>
                                        
                                    <div class="form-group">
                                        <label for="password" class="col-md-3 control-label">Confirm Password</label>
                                        <div class="col-md-9">
                                            <input type="password" id="password2" class="form-control" name="password2" placeholder="Password Re-entry">
                                        </div>
                                    </div>

                                    <!-- File Button --> 
                                    <div class="form-group">
                                        <label class="col-md-3 control-label" for="pic">Profile Picture</label>
                                        <div class="col-md-9">
                                            <input id="pic" name="pic" class="input-file" type="file">
                                        </div>
                                    </div>

                                    <!-- Textarea -->
                                    <div class="form-group">
                                        <label class="col-md-3 control-label" for="role">Role In Project</label>
                                        <div class="col-md-9">                     
                                            <textarea class="form-control" id="role" name="role"></textarea>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <!-- Button -->                                        
                                        <div class="col-md-offset-3 col-md-9">
                                            <button id="btn-signup" type="submit" class="btn btn-info"><i class="icon-hand-right"></i> &nbsp Sign Up</button>
                                        </div>
                                    </div>

                                 </form>
                            </div>
                        </div>
            </div> 
        </div>
<footer class="navbar navbar-fixed-bottom" id="footer">

</footer>



    <script src="js/ie10-viewport-bug-workaround.js"></script>
    <script src="bower_components/jquery/dist/jquery.js"></script>
    <script src="bower_components/bootstrap/dist/js/bootstrap.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery.bootstrapvalidator/0.5.3/js/bootstrapValidator.js"></script>
    <script src="js/main.js"></script>    
</body>
</html>